2021-11-14 16:14:03 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration lovelace_gen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration weatherbit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration myenergi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration media_player_template which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration myq which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:03 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-14 16:14:20 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'state' when rendering '<ha-icon icon="mdi:home-assistant"></ha-icon>&nbsp;**Add-on update:** &nbsp;&nbsp; {{ states.sensor.supervisor_updates.state }}

> {% for addon in states.sensor.supervisor_updates.attributes.addons %}
> {{ addon.name }}&nbsp; {{ addon.version }} -> {{ addon.version_latest }}
> {% endfor %}

<ha-icon icon="hacs:hacs"></ha-icon>&nbsp;**HACS updates:** &nbsp;&nbsp; {{ states.sensor.hacs.state }}

> {% for repo in states.sensor.hacs.attributes.repositories %}
>  **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{repo["available_version"] }}_
> {% endfor %}'
2021-11-14 16:14:20 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '<ha-icon icon="mdi:home-assistant"></ha-icon>&nbsp;**Add-on update:** &nbsp;&nbsp; {{ states.sensor.supervisor_updates.state }}

> {% for addon in states.sensor.supervisor_updates.attributes.addons %}
> {{ addon.name }}&nbsp; {{ addon.version }} -> {{ addon.version_latest }}
> {% endfor %}

<ha-icon icon="hacs:hacs"></ha-icon>&nbsp;**HACS updates:** &nbsp;&nbsp; {{ states.sensor.hacs.state }}

> {% for repo in states.sensor.hacs.attributes.repositories %}
>  **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{repo["available_version"] }}_
> {% endfor %}'
2021-11-14 16:14:20 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'state' when rendering '<ha-icon icon="mdi:home-assistant"></ha-icon>&nbsp;**Add-ons needing update:** &nbsp;&nbsp; {{ states.sensor.supervisor_updates.state }}

> {% for addon in states.sensor.supervisor_updates.attributes.addons %}
> {{ addon.name }}&nbsp; {{ addon.version }} -> {{ addon.version_latest }}
> {% endfor %}

<ha-icon icon="hacs:hacs"></ha-icon>&nbsp;**HACS updates available:** &nbsp;&nbsp; {{ states.sensor.hacs.state }}

> {% for repo in states.sensor.hacs.attributes.repositories %}
>    **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
> {% endfor %}
---
|          | Current&nbsp;&nbsp;&nbsp; |   Latest  |
|--- |:---: |:---:           |
| **Supervisor**&nbsp;&nbsp;&nbsp;    | {{ states.sensor.supervisor_updates.attributes.current_version }} | {{ states.sensor.supervisor_updates.attributes.newest_version }} |
| **Core**          | {{ states.sensor.updater_core.attributes.current_version }} | {{ states.sensor.updater_core.attributes.newest_version }} |
| **Audio**         | {{ states.sensor.updater_audio.attributes.current_version }} | {{ states.sensor.updater_audio.attributes.newest_version }} |
| **CLI**           | {{ states.sensor.updater_cli.attributes.current_version }} | {{ states.sensor.updater_cli.attributes.newest_version }} |
| **DNS**           | {{ states.sensor.updater_dns.attributes.current_version }} |  {{ states.sensor.updater_dns.attributes.newest_version }} |
| **OS**            | {{ states.sensor.os_updates.attributes.installed_version }} | {{ states.sensor.os_updates.attributes.latest_version }} |
| **Multicast**     | {{ states.sensor.updater_multicast.attributes.current_version }} |  {{ states.sensor.updater_multicast.attributes.newest_version }} |'
2021-11-14 16:14:20 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '<ha-icon icon="mdi:home-assistant"></ha-icon>&nbsp;**Add-ons needing update:** &nbsp;&nbsp; {{ states.sensor.supervisor_updates.state }}

> {% for addon in states.sensor.supervisor_updates.attributes.addons %}
> {{ addon.name }}&nbsp; {{ addon.version }} -> {{ addon.version_latest }}
> {% endfor %}

<ha-icon icon="hacs:hacs"></ha-icon>&nbsp;**HACS updates available:** &nbsp;&nbsp; {{ states.sensor.hacs.state }}

> {% for repo in states.sensor.hacs.attributes.repositories %}
>    **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
> {% endfor %}
---
|          | Current&nbsp;&nbsp;&nbsp; |   Latest  |
|--- |:---: |:---:           |
| **Supervisor**&nbsp;&nbsp;&nbsp;    | {{ states.sensor.supervisor_updates.attributes.current_version }} | {{ states.sensor.supervisor_updates.attributes.newest_version }} |
| **Core**          | {{ states.sensor.updater_core.attributes.current_version }} | {{ states.sensor.updater_core.attributes.newest_version }} |
| **Audio**         | {{ states.sensor.updater_audio.attributes.current_version }} | {{ states.sensor.updater_audio.attributes.newest_version }} |
| **CLI**           | {{ states.sensor.updater_cli.attributes.current_version }} | {{ states.sensor.updater_cli.attributes.newest_version }} |
| **DNS**           | {{ states.sensor.updater_dns.attributes.current_version }} |  {{ states.sensor.updater_dns.attributes.newest_version }} |
| **OS**            | {{ states.sensor.os_updates.attributes.installed_version }} | {{ states.sensor.os_updates.attributes.latest_version }} |
| **Multicast**     | {{ states.sensor.updater_multicast.attributes.current_version }} |  {{ states.sensor.updater_multicast.attributes.newest_version }} |'
2021-11-14 16:14:20 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'state' when rendering '<ha-icon icon="mdi:home-assistant"></ha-icon>&nbsp;**Add-on update:** &nbsp;&nbsp; {{ states.sensor.supervisor_updates.state }}

> {% for addon in states.sensor.supervisor_updates.attributes.addons %}
> {{ addon.name }}&nbsp; {{ addon.version }} -> {{ addon.version_latest }}
> {% endfor %}

<ha-icon icon="hacs:hacs"></ha-icon>&nbsp;**HACS updates:** &nbsp;&nbsp; {{ states.sensor.hacs.state }}

> {% for repo in states.sensor.hacs.attributes.repositories %}
>  **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{repo["available_version"] }}_
> {% endfor %}'
2021-11-14 16:14:20 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '<ha-icon icon="mdi:home-assistant"></ha-icon>&nbsp;**Add-on update:** &nbsp;&nbsp; {{ states.sensor.supervisor_updates.state }}

> {% for addon in states.sensor.supervisor_updates.attributes.addons %}
> {{ addon.name }}&nbsp; {{ addon.version }} -> {{ addon.version_latest }}
> {% endfor %}

<ha-icon icon="hacs:hacs"></ha-icon>&nbsp;**HACS updates:** &nbsp;&nbsp; {{ states.sensor.hacs.state }}

> {% for repo in states.sensor.hacs.attributes.repositories %}
>  **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{repo["available_version"] }}_
> {% endfor %}'
2021-11-14 16:14:20 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'state' when rendering '<ha-icon icon="mdi:home-assistant"></ha-icon>&nbsp;**Add-on update:** &nbsp;&nbsp; {{ states.sensor.supervisor_updates.state }}

> {% for addon in states.sensor.supervisor_updates.attributes.addons %}
> {{ addon.name }}&nbsp; {{ addon.version }} -> {{ addon.version_latest }}
> {% endfor %}

<ha-icon icon="hacs:hacs"></ha-icon>&nbsp;**HACS updates:** &nbsp;&nbsp; {{ states.sensor.hacs.state }}

> {% for repo in states.sensor.hacs.attributes.repositories %}
>  **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{repo["available_version"] }}_
> {% endfor %}'
2021-11-14 16:14:20 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '<ha-icon icon="mdi:home-assistant"></ha-icon>&nbsp;**Add-on update:** &nbsp;&nbsp; {{ states.sensor.supervisor_updates.state }}

> {% for addon in states.sensor.supervisor_updates.attributes.addons %}
> {{ addon.name }}&nbsp; {{ addon.version }} -> {{ addon.version_latest }}
> {% endfor %}

<ha-icon icon="hacs:hacs"></ha-icon>&nbsp;**HACS updates:** &nbsp;&nbsp; {{ states.sensor.hacs.state }}

> {% for repo in states.sensor.hacs.attributes.repositories %}
>  **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{repo["available_version"] }}_
> {% endfor %}'
2021-11-14 16:14:34 WARNING (SyncWorker_5) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: /custom_components/mail_and_packages/mail_none.gif
2021-11-14 16:14:34 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2021-11-14 16:14:35 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2021-11-14 16:14:35 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2021-11-14 16:14:35 WARNING (MainThread) [alexapy.alexalogin] No access token found; falling back to credential login instead of oauth.
2021-11-14 16:14:35 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Home' for accuweather integration not ready yet; Retrying in background
2021-11-14 16:14:42 WARNING (MainThread) [homeassistant.setup] Setup of webostv is taking over 10 seconds.
2021-11-14 16:14:44 WARNING (MainThread) [homeassistant.setup] Setup of automation is taking over 10 seconds.
2021-11-14 16:14:55 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform pirateweather is taking over 10 seconds.
2021-11-14 16:14:55 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform command_line is taking over 10 seconds.
2021-11-14 16:14:58 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.115 @ 192.168.1.115: Error connecting to ('192.168.1.115', 6053): [Errno 113] Connect call failed ('192.168.1.115', 6053)
2021-11-14 16:15:03 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.ddwart_run_time_mins=1704.08; unit_of_measurement=mins, friendly_name=DDWart Run Time @ 2021-11-14T16:15:03.554428-05:00>)>' when rendering template '{% set time = (states.sensor.ddwart_run_time_mins | int) | int %} {% set minutes = ((time % 3600) / 60) | int %} {% set hours = ((time % 86400) / 3600) | int %} {% set days = (time / 86400) | int %}
{% if time == 0 %}
  Just restarted...
 {%- else -%}
  {%- if days > 0 -%}
    {{ days }}d
  {%- endif -%}
  {%- if hours > 0 -%}
    {%- if days > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ hours }}h
  {%- endif -%}
  {%- if minutes > 0 -%}
    {%- if days > 0 or hours > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ minutes }}m
  {%- endif -%}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-14 16:15:03 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.ddwart_run_time_mins=1704.08; unit_of_measurement=mins, friendly_name=DDWart Run Time @ 2021-11-14T16:15:03.554428-05:00>)>' when rendering template '{% set time = (states.sensor.ddwart_run_time_mins | int) | int %} {% set minutes = ((time % 3600) / 60) | int %} {% set hours = ((time % 86400) / 3600) | int %} {% set days = (time / 86400) | int %}
{% if time == 0 %}
  Just restarted...
 {%- else -%}
  {%- if days > 0 -%}
    {{ days }}d
  {%- endif -%}
  {%- if hours > 0 -%}
    {%- if days > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ hours }}h
  {%- endif -%}
  {%- if minutes > 0 -%}
    {%- if days > 0 or hours > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ minutes }}m
  {%- endif -%}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-14 16:15:03 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.netgear_r6400_v2_ewvisualarts_uptime=102245; unit_of_measurement=s, friendly_name=Netgear R6400 v2:EWVisualArts Uptime, icon=mdi:server-network @ 2021-11-14T16:15:00.945054-05:00>)>' when rendering template '{% set uptime = states.sensor.netgear_r6400_v2_ewvisualarts_uptime | int %} {% set days = (uptime / 86400) | int %} {%- if days > 0 -%}
  {{ days }} days, {{ (uptime - (days * 86400)) | int | timestamp_custom('%H:%M:%S', false) }}
{%- else -%}
  {{ uptime | int | timestamp_custom('%H:%M:%S', false) }}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-14 16:15:03 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.netgear_r6400_v2_ewvisualarts_uptime=102245; unit_of_measurement=s, friendly_name=Netgear R6400 v2:EWVisualArts Uptime, icon=mdi:server-network @ 2021-11-14T16:15:00.945054-05:00>)>' when rendering template '{% set uptime = states.sensor.netgear_r6400_v2_ewvisualarts_uptime | int %} {% set days = (uptime / 86400) | int %} {%- if days > 0 -%}
  {{ days }} days, {{ (uptime - (days * 86400)) | int | timestamp_custom('%H:%M:%S', false) }}
{%- else -%}
  {{ uptime | int | timestamp_custom('%H:%M:%S', false) }}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-14 16:15:06 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'unavailable' when rendering template '{% set up_time =  as_timestamp(now()) - as_timestamp(states('sensor.ewvisualarts_last_boot')) %}
{% if up_time == 0 %}
  Just restarted...
{% else %}
  {% set minutes = (up_time // 60) | int %}
  {% set hours = (minutes // 60) %}
  {% set days = (hours // 24) %}
  {% set weeks = (days // 7) %}

  {% set minutes = (minutes % 60) %}
  {% set hours =  (hours % 24) %}
  {% set days = (days % 7) %}

  {% macro phrase(value, name) %}
            {%- set value = value %}
            {%- set end = 's' if value > 1 else '' %}
            {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
  {%- endmacro %}

  {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
  {% set last_comma = text.rfind(',') %}
  {% if last_comma != -1 %}
    {% set text = text[:last_comma] + '' + text[last_comma + 1:] %}
  {% endif %}

{{ text }}
{% endif %}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-14 16:15:06 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'') while processing template 'Template("{% set up_time =  as_timestamp(now()) - as_timestamp(states('sensor.ewvisualarts_last_boot')) %}
{% if up_time == 0 %}
  Just restarted...
{% else %}
  {% set minutes = (up_time // 60) | int %}
  {% set hours = (minutes // 60) %}
  {% set days = (hours // 24) %}
  {% set weeks = (days // 7) %}

  {% set minutes = (minutes % 60) %}
  {% set hours =  (hours % 24) %}
  {% set days = (days % 7) %}

  {% macro phrase(value, name) %}
            {%- set value = value %}
            {%- set end = 's' if value > 1 else '' %}
            {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
  {%- endmacro %}

  {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
  {% set last_comma = text.rfind(',') %}
  {% if last_comma != -1 %}
    {% set text = text[:last_comma] + '' + text[last_comma + 1:] %}
  {% endif %}

{{ text }}
{% endif %}")' for attribute '_attr_native_value' in entity 'sensor.uptime_synology_nas'
2021-11-14 16:15:06 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 162, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-14 16:15:06 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 368, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-14 16:15:06 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-14 16:15:06 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 85, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-14 16:15:17 WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval 0:00:10
2021-11-14 16:15:17 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.mancave_tv is taking over 10 seconds
2021-11-14 16:15:17 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.livingroom_tv is taking over 10 seconds
2021-11-14 16:15:23 WARNING (MainThread) [homeassistant.components.media_player] Updating alexa_media media_player took longer than the scheduled update interval 0:00:10
2021-11-14 16:15:33 ERROR (SyncWorker_2) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiopylgtv/webos_client.py", line 340, in ping_handler
    ping_waiter = await ws.ping()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 657, in ping
    await self.ensure_open()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason
2021-11-14 16:15:33 ERROR (SyncWorker_2) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiopylgtv/webos_client.py", line 340, in ping_handler
    ping_waiter = await ws.ping()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 657, in ping
    await self.ensure_open()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason
2021-11-14 16:15:41 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform synology_dsm is taking over 10 seconds.
2021-11-14 16:15:41 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform synology_dsm is taking over 10 seconds.
2021-11-14 16:15:41 WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval 0:00:10
2021-11-14 16:15:41 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.mancave_tv is taking over 10 seconds
2021-11-14 16:15:41 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.livingroom_tv is taking over 10 seconds
2021-11-14 17:06:43 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.84 @ 192.168.1.84: Timeout while connecting to ('192.168.1.84', 6053)
2021-11-14 17:09:45 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.198 @ 192.168.1.198: Timeout while connecting to ('192.168.1.198', 6053)
2021-11-14 17:14:22 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
