2022-10-22 21:04:45.832 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.835 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.838 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration lovelace_gen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.840 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration myenergi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.844 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.851 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.854 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.858 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.861 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration holidays which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.864 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration media_player_template which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.869 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration myq which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.873 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.876 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.879 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:04:45.886 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-22 21:05:02.425 WARNING (MainThread) [homeassistant.components.template.config] The entity definition format under template: differs from the platform configuration format. See https://www.home-assistant.io/integrations/template#configuration-for-trigger-based-template-sensors
2022-10-22 21:05:02.510 WARNING (MainThread) [homeassistant.components.template.config] The entity definition format under template: differs from the platform configuration format. See https://www.home-assistant.io/integrations/template#configuration-for-trigger-based-template-sensors
2022-10-22 21:05:04.334 WARNING (MainThread) [homeassistant.components.weather] custom_components.pirateweather.weather::DarkSkyWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.
2022-10-22 21:05:05.748 WARNING (SyncWorker_9) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: /custom_components/mail_and_packages/mail_none.gif
2022-10-22 21:05:07.121 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses pressure utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.PressureConverter instead. Please report issue to the custom integration author for pirateweather using this method at custom_components/pirateweather/weather.py, line 169: return round(convert_pressure(pressure, PRESSURE_HPA, PRESSURE_INHG), 2)
2022-10-22 21:05:15.150 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform pirateweather is taking over 10 seconds.
2022-10-22 21:05:17.163 WARNING (MainThread) [homeassistant.config_entries] Config entry 'GS108Tv3-785549' for upnp integration not ready yet: Device not discovered: uuid:fb8e67ba-7dba-11e7-be55-94a67e785549::urn:schemas-upnp-org:device:InternetGatewayDevice:1; Retrying in background
2022-10-22 21:05:17.592 WARNING (MainThread) [homeassistant.setup] Setup of automation is taking over 10 seconds.
2022-10-22 21:05:20.260 ERROR (MainThread) [homeassistant.components.sensor] Platform ecobee does not generate unique IDs. ID 411962146048-ei:0-temperature already exists - ignoring sensor.living_room_temperature
2022-10-22 21:05:42.017 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform homekit_controller is taking over 10 seconds.
2022-10-22 21:05:42.023 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform homekit_controller is taking over 10 seconds.
2022-10-22 21:05:42.030 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform ecobee is taking over 10 seconds.
2022-10-22 21:05:42.036 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform nut is taking over 10 seconds.
2022-10-22 21:05:42.042 WARNING (MainThread) [homeassistant.setup] Setup of mobile_app is taking over 10 seconds.
2022-10-22 21:05:42.088 ERROR (MainThread) [homeassistant.components.nut] Timeout fetching NUT resource status data
2022-10-22 21:05:42.130 WARNING (MainThread) [homeassistant.config_entries] Config entry 'benchdog93@gmail.com' for life360 integration not ready yet; Retrying in background
2022-10-22 21:05:42.646 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.gmail.com) data
2022-10-22 21:05:42.652 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data: 
2022-10-22 21:05:42.662 WARNING (MainThread) [homeassistant.config_entries] Config entry 'imap.gmail.com' for mail_and_packages integration not ready yet: None; Retrying in background
2022-10-22 21:05:47.887 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for spare-light @ 192.168.1.115: Error connecting to ('192.168.1.115', 6053): [Errno 113] Connect call failed ('192.168.1.115', 6053)
2022-10-22 21:05:47.893 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for office-network @ 192.168.1.71: Error connecting to ('192.168.1.71', 6053): [Errno 113] Connect call failed ('192.168.1.71', 6053)
2022-10-22 21:05:59.937 WARNING (SyncWorker_6) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: unavailable
2022-10-22 21:06:12.252 WARNING (MainThread) [homeassistant.components.media_player] Updating alexa_media media_player took longer than the scheduled update interval 0:00:10
2022-10-22 21:06:29.487 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.gmail.com) data
2022-10-22 21:06:29.500 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data: 
2022-10-22 21:12:54.958 WARNING (MainThread) [homeassistant.components.template.config] The entity definition format under template: differs from the platform configuration format. See https://www.home-assistant.io/integrations/template#configuration-for-trigger-based-template-sensors
2022-10-22 21:12:54.989 WARNING (MainThread) [homeassistant.components.template.config] The entity definition format under template: differs from the platform configuration format. See https://www.home-assistant.io/integrations/template#configuration-for-trigger-based-template-sensors
2022-10-23 01:54:21.137 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.gmail.com) data
2022-10-23 01:54:21.353 WARNING (SyncWorker_1) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: unavailable
2022-10-23 01:54:27.733 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:54:27.739 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:54:57.735 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:54:57.737 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:55:27.737 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:55:27.740 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:55:57.738 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:55:57.740 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:56:27.738 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:56:27.740 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:56:57.739 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:56:57.741 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:57:27.741 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:57:27.743 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:57:57.742 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:57:57.745 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:58:27.743 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:58:27.747 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:58:57.744 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:58:57.748 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:59:27.745 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 01:59:27.748 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:31:25.040 ERROR (MainThread) [custom_components.mail_and_packages] Timeout fetching Mail and Packages (imap.gmail.com) data
2022-10-23 02:31:25.164 WARNING (SyncWorker_2) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: unavailable
2022-10-23 02:31:28.970 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:31:28.973 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:31:58.971 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:31:58.976 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:32:28.972 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:32:28.976 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:32:58.974 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:32:58.979 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:33:28.976 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:33:28.978 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:33:58.977 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:33:58.981 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:34:28.979 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:34:28.981 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:34:58.979 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:34:58.984 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:35:28.980 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:35:28.984 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:35:58.982 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:35:58.989 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:36:28.983 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 02:36:28.994 WARNING (MainThread) [custom_components.mail_and_packages.camera] Update to update camera image. Unavailable.
2022-10-23 03:24:58.223 WARNING (MainThread) [homeassistant.components.synology_dsm.common] Connection error during update, fallback by reloading the entry
2022-10-23 04:50:54.660 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 04:50:54.710 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 04:50:54.713 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 04:51:08.859 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 04:51:08.870 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 04:51:08.873 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 04:52:00.963 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 04:52:00.970 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 04:52:00.974 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 05:06:33.922 WARNING (MainThread) [zigpy.appdb] Discarding _save_device_last_seen event
2022-10-23 05:06:33.947 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/zigpy/topology.py", line 52, in scan_loop
    await self.scan()
  File "/usr/local/lib/python3.10/site-packages/zigpy/topology.py", line 63, in scan
    await self._scan_task
  File "/usr/local/lib/python3.10/site-packages/zigpy/topology.py", line 86, in _scan
    await device.neighbors.scan()
  File "/usr/local/lib/python3.10/site-packages/zigpy/neighbor.py", line 96, in scan
    return await self._scan()
  File "/usr/local/lib/python3.10/site-packages/zigpy/neighbor.py", line 107, in _scan
    status, rsp = await self._device.zdo.Mgmt_Lqi_req(idx, tries=3, delay=1)
  File "/usr/local/lib/python3.10/site-packages/zigpy/util.py", line 131, in retry
    r = await func()
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 297, in request
    await self._application.request(
  File "/usr/local/lib/python3.10/site-packages/zigpy/application.py", line 654, in request
    await self.send_packet(
  File "/usr/local/lib/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 1026, in send_packet
    response = await self._send_request_raw(
  File "/usr/local/lib/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 901, in _send_request_raw
    response = await self._znp.request(
AttributeError: 'NoneType' object has no attribute 'request'
2022-10-23 05:21:44.570 WARNING (MainThread) [zigpy.appdb] Discarding _save_device_last_seen event
2022-10-23 05:21:44.576 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/zigpy/topology.py", line 52, in scan_loop
    await self.scan()
  File "/usr/local/lib/python3.10/site-packages/zigpy/topology.py", line 63, in scan
    await self._scan_task
  File "/usr/local/lib/python3.10/site-packages/zigpy/topology.py", line 86, in _scan
    await device.neighbors.scan()
  File "/usr/local/lib/python3.10/site-packages/zigpy/neighbor.py", line 96, in scan
    return await self._scan()
  File "/usr/local/lib/python3.10/site-packages/zigpy/neighbor.py", line 107, in _scan
    status, rsp = await self._device.zdo.Mgmt_Lqi_req(idx, tries=3, delay=1)
  File "/usr/local/lib/python3.10/site-packages/zigpy/util.py", line 131, in retry
    r = await func()
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 297, in request
    await self._application.request(
  File "/usr/local/lib/python3.10/site-packages/zigpy/application.py", line 654, in request
    await self.send_packet(
  File "/usr/local/lib/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 1026, in send_packet
    response = await self._send_request_raw(
  File "/usr/local/lib/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 901, in _send_request_raw
    response = await self._znp.request(
AttributeError: 'NoneType' object has no attribute 'request'
2022-10-23 05:22:37.313 WARNING (MainThread) [zigpy.appdb] Discarding _save_device_last_seen event
2022-10-23 05:22:37.319 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/zigpy/topology.py", line 52, in scan_loop
    await self.scan()
  File "/usr/local/lib/python3.10/site-packages/zigpy/topology.py", line 63, in scan
    await self._scan_task
  File "/usr/local/lib/python3.10/site-packages/zigpy/topology.py", line 86, in _scan
    await device.neighbors.scan()
  File "/usr/local/lib/python3.10/site-packages/zigpy/neighbor.py", line 96, in scan
    return await self._scan()
  File "/usr/local/lib/python3.10/site-packages/zigpy/neighbor.py", line 107, in _scan
    status, rsp = await self._device.zdo.Mgmt_Lqi_req(idx, tries=3, delay=1)
  File "/usr/local/lib/python3.10/site-packages/zigpy/util.py", line 131, in retry
    r = await func()
  File "/usr/local/lib/python3.10/site-packages/zigpy/device.py", line 297, in request
    await self._application.request(
  File "/usr/local/lib/python3.10/site-packages/zigpy/application.py", line 654, in request
    await self.send_packet(
  File "/usr/local/lib/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 1026, in send_packet
    response = await self._send_request_raw(
  File "/usr/local/lib/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 901, in _send_request_raw
    response = await self._znp.request(
AttributeError: 'NoneType' object has no attribute 'request'
2022-10-23 05:38:32.643 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 05:38:32.652 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 05:38:32.655 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 05:38:52.533 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 05:38:52.546 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 05:38:52.550 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 05:39:54.284 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 05:39:54.298 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 05:39:54.305 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 05:44:04.096 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 05:44:04.103 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 05:44:04.109 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 05:44:27.532 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 05:44:27.534 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 05:44:27.536 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 05:44:45.531 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 05:44:45.535 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 05:44:45.537 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 06:19:52.062 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 06:19:52.065 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 06:19:52.078 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 06:20:33.461 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 06:20:33.467 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 06:20:33.470 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 06:21:41.057 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 06:21:41.061 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 06:21:41.064 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 07:07:18.903 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 07:07:18.911 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 07:07:18.917 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 07:07:31.515 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 07:07:31.518 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 07:07:31.520 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 07:07:44.783 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'command' when rendering '{{ trigger.event.data.command }}'
2022-10-23 07:07:44.787 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'cluster_id' when rendering '{{ trigger.event.data.cluster_id }}'
2022-10-23 07:07:44.790 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'endpoint_id' when rendering '{{ trigger.event.data.endpoint_id }}'
2022-10-23 08:30:00.025 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'entity_id' is undefined when rendering '{{ 'OFF_' ~ entity_id }}'
2022-10-23 08:30:00.048 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'entity_id' is undefined when rendering '{{ 'OFF_' ~ entity_id }}'
2022-10-23 08:30:00.078 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'entity_id' is undefined when rendering '{{ 'ON_' ~ entity_id }}'
2022-10-23 08:30:00.087 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'entity_id' is undefined when rendering '{{ 'OFF_' ~ entity_id }}'
2022-10-23 08:30:00.101 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'entity_id' is undefined when rendering '{{ 'OFF_' ~ entity_id }}'
2022-10-23 08:30:00.111 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'entity_id' is undefined when rendering '{{ 'OFF_' ~ entity_id }}'
2022-10-23 09:30:34.373 WARNING (MainThread) [homeassistant.components.template.config] The entity definition format under template: differs from the platform configuration format. See https://www.home-assistant.io/integrations/template#configuration-for-trigger-based-template-sensors
2022-10-23 09:30:34.378 WARNING (MainThread) [homeassistant.components.template.config] The entity definition format under template: differs from the platform configuration format. See https://www.home-assistant.io/integrations/template#configuration-for-trigger-based-template-sensors
2022-10-23 09:30:46.948 WARNING (MainThread) [homeassistant.components.template.config] The entity definition format under template: differs from the platform configuration format. See https://www.home-assistant.io/integrations/template#configuration-for-trigger-based-template-sensors
2022-10-23 09:30:46.969 WARNING (MainThread) [homeassistant.components.template.config] The entity definition format under template: differs from the platform configuration format. See https://www.home-assistant.io/integrations/template#configuration-for-trigger-based-template-sensors
2022-10-23 09:30:49.023 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
